version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: evenity
    networks:
      - doan2022
    container_name: postgres
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - doan2022
    container_name: redis
  # frontend:
  #   tty: true
  #   stdin_open: true # without this node doesn't start
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: ./Frontend__Client
  #   image: frontend
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - doan2022
  #   container_name: frontend
  core-api:
    tty: true
    stdin_open: true # without this node doesn't start
    build:
      dockerfile: ./Dockerfile
      context: ./core-api
    # depends_on:
    #   - postgres
    ports:
      - 3000:3000
    networks:
      - doan2022  
    volumes:
      - DISK1:/usr/src/app/resources
    container_name: core-api
  payment:
    tty: true
    stdin_open: true # without this node doesn't start
    build:
      dockerfile: ./Dockerfile
      context: ./payment
    # ports:
    #   - 3002:4002
    networks:
      - doan2022  
    container_name: payment
  zoom:
    tty: true
    stdin_open: true # without this node doesn't start
    build:
      dockerfile: ./Dockerfile
      context: ./zoom
    # ports:
    #   - 3001:4001
    networks:
      - doan2022  
    volumes:
      - DISK1:/usr/src/app/resources
    container_name: zoom
networks:
  doan2022:
    driver: bridge
volumes:
  DISK1: